version: "3.9"

services:
  fiber-app:
    build: app/
    container_name: fiber-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - dev

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "AUTO"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - dev

#  nginx:
#    image: nginx:stable-alpine
#    ports:
#      - "80:80"
#    depends_on:
#      - fiber-app
#    volumes:
#      - "./nginx.conf:/etc/nginx/nginx.conf"
#    networks:
#      - dev

volumes:
  data:

networks:
  dev: