version: "3.9"

services:
  fiber-app:
    build: app/
    container_name: fiber-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dev

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "AUTO"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - fiber-app
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - dev

volumes:
  postgres_data:

networks:
  dev: