version: "3.9"

networks:
  dev:

services:
  fiber-app:
    build: app/
    container_name: fiber-app
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - dev

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "AUTO"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fiber-app
      - postgres
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    networks:
      - dev

volumes:
  postgres_data: