version: "3.9"

services:
  fiber-app:
    build: app/
    container_name: fiber-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "AUTO"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: